<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Socio;

class SociosSeeder extends Seeder
{
    /**
     * Seeder de Socios del cementerio.
     * Los códigos únicos (SO-01, SO-02...) se generan automáticamente por el modelo.
     */
    public function run(): void
    {
        $socios = [
            [
                'comunidad_id' => 1,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1002638318',
                'apellidos' => 'ALVAREZ AMAGUAÑA',
                'nombres' => 'MIGUEL',
                'telefono' => '0981775372',
                'direccion' => 'Calle Chuquirawa y Vía Principal',
                'email' => null,
                'fecha_nac' => '1977-08-28',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 1,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 1,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1003664438',
                'apellidos' => 'SARANSIG PERUGACHI',
                'nombres' => 'JHON JAIRO',
                'telefono' => '0985511076',
                'direccion' => 'Urbanización San Sebastián',
                'email' => null,
                'fecha_nac' => '1993-09-04',
                'fecha_inscripcion' => '2017-01-01',
            ],
            [
                'comunidad_id' => 1,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1002813457',
                'apellidos' => 'MORALES YEPEZ',
                'nombres' => 'IRMA MARIA',
                'telefono' => '0991234567',
                'direccion' => 'Santa Rosa de la Banda, Sector Centro',
                'email' => null,
                'fecha_nac' => '1981-05-18',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 2,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001443249',
                'apellidos' => 'CAMUENDO CACHIGUANGO',
                'nombres' => 'HUMBERTO',
                'telefono' => '0969002886',
                'direccion' => 'Roca Morales y Salinas Casa 905',
                'email' => null,
                'fecha_nac' => '1964-06-04',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 3,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2020-06-30',
                'genero_id' => 2,
                'estado_civil_id' => 3,
                'condicion' => 'ninguna',
                'estatus' => 'fallecido',
                'cedula' => '1725683286',
                'apellidos' => 'MUENALA PERUGACHI',
                'nombres' => 'ROSA',
                'telefono' => '0967492186',
                'direccion' => 'Comunidad Uyancha Vía Principal',
                'email' => null,
                'fecha_nac' => '1932-04-01',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 3,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001381647',
                'apellidos' => 'OYAGATA MUENALA',
                'nombres' => 'MERCEDES',
                'telefono' => '0981799649',
                'direccion' => 'Camino Viejo, Uyancha',
                'email' => null,
                'fecha_nac' => '1961-01-14',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 4,
                'tipo_beneficio' => 'con_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001475720',
                'apellidos' => 'PERUGACHI GUALAPURO',
                'nombres' => 'PEDRO',
                'telefono' => '0989651095',
                'direccion' => 'Vía Cuicocha, Sector Punge',
                'email' => null,
                'fecha_nac' => '1958-12-26',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 5,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2022-01-05',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000853885',
                'apellidos' => 'AMAGUAÑA GUAMAN',
                'nombres' => 'JOSE',
                'telefono' => '0982233445',
                'direccion' => 'Calle Principal, Puerto Alegre',
                'email' => null,
                'fecha_nac' => '1944-04-27',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 6,
                'tipo_beneficio' => 'con_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000682557',
                'apellidos' => 'CACHIGUANGO AJALA',
                'nombres' => 'ROSA MARIA',
                'telefono' => '0993344556',
                'direccion' => 'Pedro Alarcón y Callejón de la Escuela',
                'email' => null,
                'fecha_nac' => '1956-01-07',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 7,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 1,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1723013627',
                'apellidos' => 'QUILUMBAQUIN CUASCOTA',
                'nombres' => 'BLANCA ELIZABETH',
                'telefono' => '0982905086',
                'direccion' => 'A dos cuadras del cementerio de Tupigachi',
                'email' => null,
                'fecha_nac' => '1983-03-23',
                'fecha_inscripcion' => '2021-01-01',
            ],
            [
                'comunidad_id' => 8,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2021-11-22',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000867786',
                'apellidos' => 'CACHIGUANGO CANDO',
                'nombres' => 'JOSE',
                'telefono' => '0969033455',
                'direccion' => 'San Nicolás de Cuicocha',
                'email' => null,
                'fecha_nac' => '1945-02-18',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 9,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2021-01-01',
                'genero_id' => 2,
                'estado_civil_id' => 3,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000614659',
                'apellidos' => 'LEMA COTACACHI',
                'nombres' => 'MARIA DOLORES',
                'telefono' => '0999640769',
                'direccion' => 'Centro de Patalanga',
                'email' => null,
                'fecha_nac' => '1949-04-09',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 10,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000994002',
                'apellidos' => 'CHAGNA MALDONADO',
                'nombres' => 'LUZ MARIA',
                'telefono' => '0980161823',
                'direccion' => 'Calle Guillermo Garzón Ubidia',
                'email' => null,
                'fecha_nac' => '1963-05-23',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 10,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000993996',
                'apellidos' => 'CHAGNA MALDONADO',
                'nombres' => 'MARIA VIRGINIA',
                'telefono' => '0990067243',
                'direccion' => 'Calle Guillermo Garzón Ubidia N43',
                'email' => null,
                'fecha_nac' => '1966-03-11',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 11,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000652873',
                'apellidos' => 'CACHIGUANGO CANDO',
                'nombres' => 'JOSE RAFAEL',
                'telefono' => '0984455667',
                'direccion' => 'Camino a Moras Punku Centro',
                'email' => null,
                'fecha_nac' => '1947-03-07',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 11,
                'tipo_beneficio' => 'con_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000842516',
                'apellidos' => 'CASTAÑEDA POTOSI',
                'nombres' => 'RAFAEL',
                'telefono' => '0995566778',
                'direccion' => 'Moras Punku Sector Norte',
                'email' => null,
                'fecha_nac' => '1952-12-30',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 12,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2020-08-19',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001503299',
                'apellidos' => 'GUITARRA MAIGUA',
                'nombres' => 'JOSE RAFAEL',
                'telefono' => '0997156259',
                'direccion' => 'Centro Comunitario Minas Chupa',
                'email' => null,
                'fecha_nac' => '1942-07-25',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 12,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 3,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1708342082',
                'apellidos' => 'PANAMA LANCHIMBA',
                'nombres' => 'TRANSITO',
                'telefono' => '0992987815',
                'direccion' => 'Calle Principal Minas Chupa',
                'email' => null,
                'fecha_nac' => '1964-06-01',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 13,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1708772775',
                'apellidos' => 'ROJAS TONTAQUIMBA',
                'nombres' => 'MARIANA ELENA',
                'telefono' => '0939303278',
                'direccion' => 'Sector Pinsaqui / Pedro Frayle',
                'email' => null,
                'fecha_nac' => '1966-06-12',
                'fecha_inscripcion' => '2021-01-01',
            ],
            [
                'comunidad_id' => 14,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001728730',
                'apellidos' => 'GUALAPURO MARCILLO',
                'nombres' => 'MARIA ROSA',
                'telefono' => '0992269291',
                'direccion' => 'Vía Principal Gualapuro',
                'email' => null,
                'fecha_nac' => '1969-02-26',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 15,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 1,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1003150636',
                'apellidos' => 'MUENALA CAMPO',
                'nombres' => 'EDISON FERNANDO',
                'telefono' => '0992222404',
                'direccion' => 'Av. Corazas y José Sanchez',
                'email' => null,
                'fecha_nac' => '1988-11-07',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 15,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2022-02-04',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000047181',
                'apellidos' => 'CACHIMUEL MALDONADO',
                'nombres' => 'JOSE MIGUEL',
                'telefono' => '0991186557',
                'direccion' => 'Calle Principal San Juan',
                'email' => null,
                'fecha_nac' => '1939-02-21',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 15,
                'tipo_beneficio' => 'con_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000908713',
                'apellidos' => 'ZAMBRANO CACHIMUEL',
                'nombres' => 'MARIA LUCIA',
                'telefono' => '0986052962',
                'direccion' => 'San Juan Capilla Central',
                'email' => null,
                'fecha_nac' => '1955-04-16',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 15,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 2,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1708826720',
                'apellidos' => 'TITUAÑA GUALAPURO',
                'nombres' => 'ROSA ELENA',
                'telefono' => '0986203392',
                'direccion' => 'Calle Inti Raymi',
                'email' => null,
                'fecha_nac' => '1966-06-09',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 16,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2021-01-01',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000739373',
                'apellidos' => 'OTAVALO ISAMA',
                'nombres' => 'JOSE',
                'telefono' => '0981122334',
                'direccion' => 'A 2 Cuadras del Estadio',
                'email' => null,
                'fecha_nac' => '1946-08-16',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 16,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1002178422',
                'apellidos' => 'AGUILAR ANRANGO',
                'nombres' => 'JOSE REMIGIO',
                'telefono' => '0981419719',
                'direccion' => 'Calle Principal Imbabuela',
                'email' => null,
                'fecha_nac' => '1973-11-20',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 16,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 1,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1004089122',
                'apellidos' => 'AGUILAR OTAVALO',
                'nombres' => 'LUIS GABRIEL',
                'telefono' => '0989383880',
                'direccion' => 'Calle Principal Imbabuela',
                'email' => null,
                'fecha_nac' => '1996-08-24',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 16,
                'tipo_beneficio' => 'exonerado',
                'fecha_exoneracion' => '2021-01-01',
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000852333',
                'apellidos' => 'VELASQUEZ ANRANGO',
                'nombres' => 'SEGUNDO',
                'telefono' => '0969174393',
                'direccion' => 'Centro Imbabuela Bajo',
                'email' => null,
                'fecha_nac' => '1945-06-13',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 17,
                'tipo_beneficio' => 'sin_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1001338407',
                'apellidos' => 'YAMBERLA MORETA',
                'nombres' => 'ESTEBAN',
                'telefono' => '0999559495',
                'direccion' => 'Guanansi Alto',
                'email' => null,
                'fecha_nac' => '1959-10-16',
                'fecha_inscripcion' => '2015-01-01',
            ],
            [
                'comunidad_id' => 18,
                'tipo_beneficio' => 'con_subsidio',
                'fecha_exoneracion' => null,
                'genero_id' => 1,
                'estado_civil_id' => 2,
                'condicion' => 'ninguna',
                'estatus' => 'vivo',
                'cedula' => '1000857126',
                'apellidos' => 'CASTAÑEDA ANDRANGO',
                'nombres' => 'ANGEL JAIRO',
                'telefono' => '0992032568',
                'direccion' => 'Sector Parca Yaku',
                'email' => null,
                'fecha_nac' => '1954-09-26',
                'fecha_inscripcion' => '2015-01-01',
            ],
        ];

        $count = 0;
        foreach ($socios as $data) {
            $socio = Socio::create($data);
            $count++;
            $this->command->info("  ✅ SO-{$count}: {$socio->apellidos} {$socio->nombres} ({$socio->codigo})");
        }

        $this->command->info("");
        $this->command->info("══════════════════════════════════════════");
        $this->command->info("✅ Seeder de Socios completado: {$count} socios creados");
        $this->command->info("══════════════════════════════════════════");
    }
}
